// Write site/public/_headers before each build.
//
// Cloudflare's _headers format has no hostname wildcard, so a static file
// cannot say "noindex unless this is production". Generating it from the same
// SITE_URL that drives the meta robots tag keeps the two signals from ever
// disagreeing — the failure mode being a staging deploy that says noindex in
// HTML but serves an indexable sitemap.xml.
//
//   SITE_URL=https://dev.alphaefficiency.com node scripts/gen-headers.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const SITE = process.env.SITE_URL ?? 'https://alphaefficiency.com';
const IS_PROD = SITE === 'https://alphaefficiency.com';

// Anchored to this file, not process.cwd(): npm runs `prebuild` with site/ as
// the working directory, so a cwd-relative path silently writes to
// site/site/public/_headers and the real one is never updated.
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, 'site', 'public', '_headers');

const header = `# Generated by scripts/gen-headers.mjs — do not edit by hand.\n# Built for ${SITE}\n`;

const body = IS_PROD
  ? `
# Production build: no robots restrictions.
/*
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
`
  : `
# Non-production build: block indexing at the header level too, so non-HTML
# responses (sitemap.xml, feeds) are covered as well as pages.
/*
  X-Robots-Tag: noindex, nofollow
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin

# Prerendered documents are static assets, so they never reach the SSR
# middleware that sets no-store. Without these two rules the project URL keeps
# serving a stale homepage after a deploy and you have to fall back to a
# per-deployment hash URL to see your own changes. Assets are deliberately
# left cacheable.
/
  Cache-Control: no-store, must-revalidate

/*.html
  Cache-Control: no-store, must-revalidate
`;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, header + body);
console.log(`_headers -> ${IS_PROD ? 'PRODUCTION (indexable)' : 'STAGING (noindex)'} for ${SITE}`);
